# ~/.profile is not read by bash if ~/.bash_profile or ~/.bash_login exists
# Therefore, we force bash to source ~/.profile here:
if [ -n $BASH_VERSION ]; then
  if [ -f ${HOME}/.profile ]; then
    # source .profile if it exists
    . ${HOME}/.profile
  fi
fi

# macOS starts bash as login script, and does therefore not automatically
# source ~/.bashrc. Therefore, let this be the last lines of the file:
if [ -n $BASH_VERSION ]; then
  if [ -f ${HOME}/.bashrc ]; then
    # source .bashrc if it exists
    . ${HOME}/.bashrc
  fi
fi
